WGT_Website/golfer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.GolferListView.as_view(), name='golfer_list'),
    path('<int:pk>/', views.GolferDetailView.as_view(), name='golfer_detail'),
    path('<int:pk>/round_scores/', views.GolferRoundScoresView.as_view(), name='golfer_round_scores'),
]

WGT_Website/golfer_polls/urls.py
from django.urls import path
from . import views

app_name = 'golfer_polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

WGT_Website/wgt_site/urls.py
from django.contrib import admin
from django.urls import path, include

from golf_course import urls as golf_course_urls
from golfer import urls as golfer_urls
from tournament import urls as tournament_urls
from golfer_polls import urls as golfer_polls_urls

from . views import homepage

urlpatterns = [
    path('', homepage),
    path('admin/', admin.site.urls),
    path('golfer/', include(golfer_urls)),
    path('tournament/', include(tournament_urls)),
    path('golf_course/', include(golf_course_urls)),
    path('golfer_polls/', include(golfer_polls_urls)),
]

admin.site.site_header = 'Wake Golf Tour'
admin.site.index_title = 'WGT Site Administration'

WGT_Website/golfer_polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

WGT_Website/golfer_polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Choice, Question


class IndexView(generic.ListView):
    model = Question
    template_name = 'golfer_polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model=Question
    template_name = 'golfer_polls/detail.html'


class ResultsView(generic.DetailView):
    model=Question
    template_name = 'golfer_polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'golfer_polls/detail.html',
            {
                'question':question, 'error_message':"You didn't select a golfer.",
            })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('golfer_polls:results', args=(question.id,)))

WGT_Website/golfer_polls/templates/golfer_polls/base_golfer_polls.html
{% extends parent_template|default:"base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" type="text/css"
        href="{% static 'golfer_polls/styles.css' %}" />
{% endblock %}

{% block img %}
   <img src="{% static 'golfer_polls/golfer.jpg' %}" alt="Golfer" style="width:300px;height:300px"; />
{% endblock %}

WGT_Website/golfer_polls/templates/golfer_polls/detail.html
{% extends parent_template|default:"golfer_polls/base_golfer_polls.html" %} 
{% block title %}
{{ block.super }} - {{question.question_text}}
{% endblock %}
{% block content %}
  <h1>{{ question.question_text }}</h1>
  {% if error_message %}
    <p>
      <strong>{{ error_message }} </strong>
    </p>
  {% endif %}
  <form action="{% url 'golfer_polls:vote' question.id %}" 
        method="post">
    {% csrf_token %}
    <select name= "choice">
        <option selected="selected" 
                     disabled>Golfers
        </option>
        {% for choice in question.choice_set.all %}
           <option value= "{{choice.id}}">
                   {{choice.choice_text}}
           </option>
        {% endfor %}                
    </select>
  <input type="submit" value="Vote" />
  </form>
{% endblock %}

WGT_Website/golfer_polls/templates/golfer_polls/index.html
{% extends parent_template|default:"golfer_polls/base_golfer_polls.html" %}

{% block title %}
{{ block.super }} - {{question.question_text}}
{% endblock %}

{% block content %}
  <h2><a>Today's Poll Question:</a></h2>
  {% if latest_question_list %}
    <ul>
      {% for question in latest_question_list %}
        <li><a href="{% url 'golfer_polls:detail' question.id %}">
            {{ question.question_text }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No polls are available.</p>
  {% endif %}
{% endblock %}

WGT_Website/golfer_polls/templates/golfer_polls/results.html
{% extends parent_template|default:"golfer_polls/base_golfer_polls.html" %}

{% block title %}
{{ block.super }} - {{question.question_text}}
{% endblock %}

{% block content %}

    <h2><a>Poll Results</a></h2>
    <ul>
    {% for choice in question.choice_set.all|dictsortreversed:"votes" %}
        {% if choice.votes > 0 %}
            <li>{{choice.choice_text}} -- {{choice.votes}}
                       vote{{choice.votes|pluralize}}</li>
        {% endif %}
    {%endfor%}
    </ul>
    <a href="{% url 'golfer_polls:detail' question.id %}">Vote again?</a> 
    
{% endblock %}