WGT_Website/golfer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.GolferListView.as_view(), name='golfer_list'),
    path('<int:pk>/', views.GolferDetailView.as_view(), name='golfer_detail'),
    path('<int:pk>/round_scores/', views.GolferRoundScoresView.as_view(), name='golfer_round_scores'),
]

WGT_Website/golfer_polls/urls.py
from django.urls import path
from . import views

app_name = 'golfer_polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

WGT_Website/wgt_site/urls.py
from django.contrib import admin
from django.urls import path, include

from golf_course import urls as golf_course_urls
from golfer import urls as golfer_urls
from tournament import urls as tournament_urls
from golfer_polls import urls as golfer_polls_urls

from . views import homepage

urlpatterns = [
    path('', homepage),
    path('admin/', admin.site.urls),
    path('golfer/', include(golfer_urls)),
    path('tournament/', include(tournament_urls)),
    path('golf_course/', include(golf_course_urls)),
    path('golfer_polls/', include(golfer_polls_urls)),
]

admin.site.site_header = 'Wake Golf Tour'
admin.site.index_title = 'WGT Site Administration'

WGT_Website/tournament/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from golf_course.models import GolfCourse


class Tournament(models.Model):
    tourn_id = models.AutoField(primary_key=True)
    tourn_name = models.TextField()
    tourn_course = models.ForeignKey(GolfCourse, models.DO_NOTHING)
    tourn_start_date = models.DateField()
    tourn_num_rounds = models.IntegerField()
    tourn_num_golfers = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'Tournament'

    def __str__(self):
        return self.tourn_name


class Round(models.Model):
    round_id = models.AutoField(primary_key=True)
    round_tourn = models.ForeignKey(Tournament, models.DO_NOTHING)
    round_day = models.TextField()

    class Meta:
        managed = False
        db_table = 'Round'

    def __str__(self):
        return ("{}".format (self.round_day))

WGT_Website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
        Wake Golf Tour
      {% endblock %}
    </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block css %}
    {% endblock %}
  </head>
  <body>
    <div>
      <header>
          <h1>Wake Golf Tour</h1>
          <p>{% block img %}
             {% endblock %}
          </p>
      </header>
      <nav>
        <ul>
          <li><a href="{% url 'golf_course_list' %}">
               Golf Courses</a></li>
          <li><a href="{% url 'golfer_list' %}">
               Golfers</a></li>
          <li><a href="{% url 'tournament_list' %}">
               Tournaments</a></li>
		  <li><a href="{% url 'golfer_polls:index' %}">
               Golfer Polls</a></li> 
        </ul>
      </nav>
      <main>
        {% block content %}
          This is where the above hyperlink lists are displayed
        {% endblock %}
      </main>
    </div>
    <footer>
      <p>
        For professional golf information: 
        <a href="http://www.pgatour.com/">PGA Tour</a>
      </p>
    </footer>
  </body>
</html>